server.port=8010
self.url=http://localhost:8010
thirdeye.uniqueId = 1
thirdeye.uniqueCode = abcdefgh
thirdeye.frontend.urls=${FRONTEND_URLS}
thirdeye.call.services=${CALL_SERVICES}
thirdeye.services.urls=${BACKEND_URLS}
eureka.client.service-url.defaultZone=${SERVER_URL}
thirdeye.redis.enabled=true
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.redis.timeout=60000


