server.port=${PORT}
self.url=${CURRENT_URL}
thirdeye.uniqueId = ${UNIQUE_ID:1}
thirdeye.uniqueCode = ${UNIQUE_CODE:abcdefgh}
thirdeye.frontend.urls=${FRONTEND_URLS}
thirdeye.call.services=${CALL_SERVICES}
thirdeye.services.urls=${BACKEND_URLS}
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=true
eureka.client.service-url.defaultZone=${SERVER_URL}

thirdeye.redis.enabled=true
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

