spring.application.name=THiRDEYE30-GATEWAY
spring.profiles.active=${PROFILE}
thirdeye.priority=1
thirdeye.api.key=${THIRDEYE_API_KEY}
thirdeye.jwt.secret=${THIRDEYE_JWT_SECRET_KEY}
thirdeye.jwt.token.starter=${THIRDEYE_TOKEN_STARTER}
telegrambot.api.key=${TELEGRAMBOT_API_KEY}
webscrapper.api.key=${WEBSCRAPPER_API_KEY}
thirdeye.open-api=${OPEN_URLS}
thirdeye.user-api=${USER_URLS}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=THIRDEYE30-MESSAGEBROKER-TELEGRAMBOT
spring.cloud.gateway.routes[0].uri=lb://THIRDEYE30-MESSAGEBROKER
spring.cloud.gateway.routes[0].predicates[0]=Path=/mb/message/telegrambot/**
spring.cloud.gateway.routes[0].filters[0]=TelegrambotApiKeyFilter
spring.cloud.gateway.routes[0].filters[1].name=Retry
spring.cloud.gateway.routes[0].filters[1].args.retries=3
spring.cloud.gateway.routes[0].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[0].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[0].filters[1].args.methods=GET
spring.cloud.gateway.routes[0].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[0].filters[1].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[0].filters[1].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[0].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[0].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[1].id=THIRDEYE30-PROPERTYMANAGER-TELEGRAMBOT
spring.cloud.gateway.routes[1].uri=lb://THIRDEYE30-PROPERTYMANAGER
spring.cloud.gateway.routes[1].predicates[0]=Path=/pm/properties/telegrambot/**
spring.cloud.gateway.routes[1].filters[0]=TelegrambotApiKeyFilter
spring.cloud.gateway.routes[1].filters[1].name=Retry
spring.cloud.gateway.routes[1].filters[1].args.retries=3
spring.cloud.gateway.routes[1].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[1].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[1].filters[1].args.methods=GET
spring.cloud.gateway.routes[1].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[1].filters[1].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[1].filters[1].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[1].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[1].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[2].id=THIRDEYE30-PROPERTYMANAGER-WEBSCRAPPER
spring.cloud.gateway.routes[2].uri=lb://THIRDEYE30-PROPERTYMANAGER
spring.cloud.gateway.routes[2].predicates[0]=Path=/pm/properties/webscrapper/**
spring.cloud.gateway.routes[2].filters[0]=WebscrapperApiKeyFilter
spring.cloud.gateway.routes[2].filters[1].name=Retry
spring.cloud.gateway.routes[2].filters[1].args.retries=3
spring.cloud.gateway.routes[2].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[2].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[2].filters[1].args.methods=GET
spring.cloud.gateway.routes[2].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[2].filters[1].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[2].filters[1].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[2].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[2].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[3].id=THIRDEYE30-STOCKMANAGER-WEBSCRAPPER
spring.cloud.gateway.routes[3].uri=lb://THIRDEYE30-STOCKMANAGER
spring.cloud.gateway.routes[3].predicates[0]=Path=/sm/stocks/webscrapper/**
spring.cloud.gateway.routes[3].filters[0]=WebscrapperApiKeyFilter
spring.cloud.gateway.routes[3].filters[1].name=Retry
spring.cloud.gateway.routes[3].filters[1].args.retries=3
spring.cloud.gateway.routes[3].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[3].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[3].filters[1].args.methods=GET
spring.cloud.gateway.routes[3].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[3].filters[1].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[3].filters[1].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[3].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[3].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[4].id=THIRDEYE30-STOCKVIEWER-WEBSCRAPPER
spring.cloud.gateway.routes[4].uri=lb://THIRDEYE30-STOCKVIEWER
spring.cloud.gateway.routes[4].predicates[0]=Path=/sv/webscrapper/**
spring.cloud.gateway.routes[4].filters[0]=WebscrapperApiKeyFilter
spring.cloud.gateway.routes[4].filters[1].name=Retry
spring.cloud.gateway.routes[4].filters[1].args.retries=3
spring.cloud.gateway.routes[4].filters[1].args.series=SERVER_ERROR
spring.cloud.gateway.routes[4].filters[1].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[4].filters[1].args.methods=GET
spring.cloud.gateway.routes[4].filters[1].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[4].filters[1].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[4].filters[1].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[4].filters[1].args.backoff.factor=2
spring.cloud.gateway.routes[4].filters[1].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[5].id=THIRDEYE30-PROPERTYMANAGER
spring.cloud.gateway.routes[5].uri=lb://THIRDEYE30-PROPERTYMANAGER
spring.cloud.gateway.routes[5].predicates[0]=Path=/pm/**
spring.cloud.gateway.routes[5].filters[0].name=Retry
spring.cloud.gateway.routes[5].filters[0].args.retries=3
spring.cloud.gateway.routes[5].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[5].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[5].filters[0].args.methods=GET
spring.cloud.gateway.routes[5].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[5].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[5].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[5].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[5].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[6].id=THIRDEYE30-MESSAGEBROKER
spring.cloud.gateway.routes[6].uri=lb://THIRDEYE30-MESSAGEBROKER
spring.cloud.gateway.routes[6].predicates[0]=Path=/mb/**
spring.cloud.gateway.routes[6].filters[0].name=Retry
spring.cloud.gateway.routes[6].filters[0].args.retries=3
spring.cloud.gateway.routes[6].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[6].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[6].filters[0].args.methods=GET
spring.cloud.gateway.routes[6].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[6].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[6].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[6].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[6].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[7].id=THIRDEYE30-STOCKMANAGER
spring.cloud.gateway.routes[7].uri=lb://THIRDEYE30-STOCKMANAGER
spring.cloud.gateway.routes[7].predicates[0]=Path=/sm/**
spring.cloud.gateway.routes[7].filters[0].name=Retry
spring.cloud.gateway.routes[7].filters[0].args.retries=3
spring.cloud.gateway.routes[7].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[7].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[7].filters[0].args.methods=GET
spring.cloud.gateway.routes[7].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[7].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[7].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[7].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[7].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[8].id=THIRDEYE30-USERMANAGER
spring.cloud.gateway.routes[8].uri=lb://THIRDEYE30-USERMANAGER
spring.cloud.gateway.routes[8].predicates[0]=Path=/um/**
spring.cloud.gateway.routes[8].filters[0].name=Retry
spring.cloud.gateway.routes[8].filters[0].args.retries=3
spring.cloud.gateway.routes[8].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[8].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[8].filters[0].args.methods=GET
spring.cloud.gateway.routes[8].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[8].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[8].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[8].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[8].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[9].id=THIRDEYE30-STOCKVIEWER
spring.cloud.gateway.routes[9].uri=lb://THIRDEYE30-STOCKVIEWER
spring.cloud.gateway.routes[9].predicates[0]=Path=/sv/**
spring.cloud.gateway.routes[9].filters[0].name=Retry
spring.cloud.gateway.routes[9].filters[0].args.retries=3
spring.cloud.gateway.routes[9].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[9].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[9].filters[0].args.methods=GET
spring.cloud.gateway.routes[9].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[9].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[9].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[9].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[9].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[10].id=THIRDEYE30-MESSENGER
spring.cloud.gateway.routes[10].uri=lb://THIRDEYE30-MESSENGER
spring.cloud.gateway.routes[10].predicates[0]=Path=/me/**
spring.cloud.gateway.routes[10].filters[0].name=Retry
spring.cloud.gateway.routes[10].filters[0].args.retries=3
spring.cloud.gateway.routes[10].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[10].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[10].filters[0].args.methods=GET
spring.cloud.gateway.routes[10].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[10].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[10].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[10].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[10].filters[0].args.backoff.basedOnPreviousValue=false

spring.cloud.gateway.routes[11].id=THIRDEYE30-EUREKASERVER
spring.cloud.gateway.routes[11].uri=${EUREKA_URL}
spring.cloud.gateway.routes[11].predicates[0]=Path=/es/**
spring.cloud.gateway.routes[11].filters[0].name=Retry
spring.cloud.gateway.routes[11].filters[0].args.retries=3
spring.cloud.gateway.routes[11].filters[0].args.series=SERVER_ERROR
spring.cloud.gateway.routes[11].filters[0].args.statuses=BAD_GATEWAY,GATEWAY_TIMEOUT
spring.cloud.gateway.routes[11].filters[0].args.methods=GET
spring.cloud.gateway.routes[11].filters[0].args.exceptions=java.io.IOException,java.util.concurrent.TimeoutException
spring.cloud.gateway.routes[11].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[11].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[11].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[11].filters[0].args.backoff.basedOnPreviousValue=false

spring.redis.lettuce.client-options.ping-before-activate-connection=true
spring.redis.timeout=60000
spring.redis.lettuce.pool.max-active=10  
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=1
spring.redis.lettuce.pool.max-wait=3000  
spring.redis.lettuce.pool.time-between-eviction-runs=60000
spring.redis.lettuce.shutdown-timeout=200ms
spring.cache.redis.cache-null-values=false   
spring.cache.redis.use-key-prefix=true
spring.data.redis.repositories.enabled=false

spring.cloud.loadbalancer.configurations=consistent-hash
spring.cloud.loadbalancer.consistent-hash.hash-header=STOCK-VIEWER-CODE

